										<div class="our_boat_route_main_nd1">
										  <div class="or_bt_top_pad"><img src="images/our_boat_rute_top.png" alt="" /></div>
										  <div class="or_bt_mid_nd1">
										  <div class="our_boat_left_nd1"><h2 class="ab_text_1">Our Route</h2><br />
										    <p>{$content.page_header}</p><br />
										  </div>
										  <div class="our_boat_right_nd1">
										 <div class="our_boat_top_nd1">
										 	<img src="images/our_boat_rute_map.jpg" alt="sightseeing, London, cruise, London rib voyages" title="sightseeing, London, cruise, London rib voyages" border="0"/><br />
<div style="position:absolute;margin-top:-121px;margin-left:26px;"><a href="#1" id="pm01" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp01" width="15" height="11" alt="" onmouseover="this.src='img/route/p/1.gif';document.getElementById('pv01').setAttribute('class','pvH');document.getElementById('pn01').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv01').setAttribute('class','our_link_txt');document.getElementById('pn01').setAttribute('class','our_link_txt');" title="Lambeth Bridge" border="0" /></a></div>	

<div style="position:absolute;margin-top:-126px;margin-left:43px;"><a href="#2" id="pm02" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp02" width="15" height="11" alt="" onmouseover="this.src='img/route/p/2.gif';document.getElementById('pv02').setAttribute('class','pvH');document.getElementById('pn02').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv02').setAttribute('class','our_link_txt');document.getElementById('pn02').setAttribute('class','our_link_txt');" title="Lambeth Palace" border="0" /></a></div>	

<div style="position:absolute;margin-top:-153px;margin-left:15px;"><a href="#3" id="pm03" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp03" width="15" height="11" alt="" onmouseover="this.src='img/route/p/3.gif';document.getElementById('pv03').setAttribute('class','pvH');document.getElementById('pn03').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv03').setAttribute('class','our_link_txt');document.getElementById('pn03').setAttribute('class','our_link_txt');" title="Houses of Parliament" border="0" /></a></div>	

<div style="position:absolute;margin-top:-170px;margin-left:31px;"><a href="#4" id="pm04" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp04" width="15" height="11" alt="" onmouseover="this.src='img/route/p/4.gif';document.getElementById('pv04').setAttribute('class','pvH');document.getElementById('pn04').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv04').setAttribute('class','our_link_txt');document.getElementById('pn04').setAttribute('class','our_link_txt');" title="Westminster Bridge" border="0" /></a></div>	

<div style="position:absolute;margin-top:-170px;margin-left:11px;"><a href="#5" id="pm05" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp05" width="15" height="11" alt="" onmouseover="this.src='img/route/p/5.gif';document.getElementById('pv05').setAttribute('class','pvH');document.getElementById('pn05').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv05').setAttribute('class','our_link_txt');document.getElementById('pn05').setAttribute('class','our_link_txt');" title="Portcullis House" border="0" /></a></div>	

<div style="position:absolute;margin-top:-173px;margin-left:49px;"><a href="#6" id="pm06" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp06" width="15" height="11" alt="" onmouseover="this.src='img/route/p/6.gif';document.getElementById('pv06').setAttribute('class','pvH');document.getElementById('pn06').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv06').setAttribute('class','our_link_txt');document.getElementById('pn06').setAttribute('class','our_link_txt');" title="County Hall" border="0" /></a></div>

<div style="position:absolute;margin-top:-190px;margin-left:19px;"><a href="#7" id="pm07" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp07" width="15" height="11" alt="" onmouseover="this.src='img/route/p/7.gif';document.getElementById('pv07').setAttribute('class','pvH');document.getElementById('pn07').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv07').setAttribute('class','our_link_txt');document.getElementById('pn07').setAttribute('class','our_link_txt');" title="MOD" border="0" /></a></div>
<div style="position:absolute;margin-top:-186px;margin-left:49px;"><a href="#8" id="pm08" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp08" width="15" height="11" alt="" onmouseover="this.src='img/route/p/8.gif';document.getElementById('pv08').setAttribute('class','pvH');document.getElementById('pn08').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv08').setAttribute('class','our_link_txt');document.getElementById('pn08').setAttribute('class','our_link_txt');" title="London Eye" border="0" /></a></div>
<div style="position:absolute;margin-top:-206px;margin-left:41px;"><a href="#9" id="pm09" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp09" width="15" height="11" alt="" onmouseover="this.src='img/route/p/9.gif';document.getElementById('pv09').setAttribute('class','pvH');document.getElementById('pn09').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv09').setAttribute('class','our_link_txt');document.getElementById('pn09').setAttribute('class','our_link_txt');" title="Golden Jubilee Bridges" border="0" /></a></div>
<div style="position:absolute;margin-top:-214px;margin-left:22px;"><a href="#10" id="pm10" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp10" width="15" height="11" alt="" onmouseover="this.src='img/route/p/10.gif';document.getElementById('pv10').setAttribute('class','pvH');document.getElementById('pn10').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv10').setAttribute('class','our_link_txt');document.getElementById('pn10').setAttribute('class','our_link_txt');" title="Charing Cross Station" border="0" /></a></div>
<div style="position:absolute;margin-top:-204px;margin-left:58px;"><a href="#11" id="pm11" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp11" width="15" height="11" alt="" onmouseover="this.src='img/route/p/11.gif';document.getElementById('pv11').setAttribute('class','pvH');document.getElementById('pn11').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv11').setAttribute('class','our_link_txt');document.getElementById('pn11').setAttribute('class','our_link_txt');" title="South Bank Centre" border="0" /></a></div>
<div style="position:absolute;margin-top:-228px;margin-left:36px;"><a href="#12" id="pm12" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp12" width="15" height="11" alt="" onmouseover="this.src='img/route/p/12.gif';document.getElementById('pv12').setAttribute('class','pvH');document.getElementById('pn12').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv12').setAttribute('class','our_link_txt');document.getElementById('pn12').setAttribute('class','our_link_txt');" title="Shell Mex House" border="0" /></a></div>
<div style="position:absolute;margin-top:-222px;margin-left:58px;"><a href="#13" id="pm13" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp13" width="15" height="11" alt="" onmouseover="this.src='img/route/p/13.gif';document.getElementById('pv13').setAttribute('class','pvH');document.getElementById('pn13').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv13').setAttribute('class','our_link_txt');document.getElementById('pn13').setAttribute('class','our_link_txt');" title="Waterloo Bridge" border="0" /></a></div>
<div style="position:absolute;margin-top:-240px;margin-left:57px;"><a href="#14" id="pm14" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp14" width="15" height="11" alt="" onmouseover="this.src='img/route/p/14.gif';document.getElementById('pv14').setAttribute('class','pvH');document.getElementById('pn14').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv14').setAttribute('class','our_link_txt');document.getElementById('pn14').setAttribute('class','our_link_txt');" title="Somerset House" border="0" /></a></div>
<div style="position:absolute;margin-top:-245px;margin-left:80px;"><a href="#15" id="pm15" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp15" width="15" height="11" alt="" onmouseover="this.src='img/route/p/15.gif';document.getElementById('pv15').setAttribute('class','pvH');document.getElementById('pn15').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv15').setAttribute('class','our_link_txt');document.getElementById('pn15').setAttribute('class','our_link_txt');" title="Temple Arch" border="0" /></a></div>
<div style="position:absolute;margin-top:-217px;margin-left:85px;"><a href="#16" id="pm16" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp16" width="15" height="11" alt="" onmouseover="this.src='img/route/p/16.gif';document.getElementById('pv16').setAttribute('class','pvH');document.getElementById('pn16').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv16').setAttribute('class','our_link_txt');document.getElementById('pn16').setAttribute('class','our_link_txt');" title="Oxo Tower" border="0" /></a></div>
<div style="position:absolute;margin-top:-228px;margin-left:113px;"><a href="#17" id="pm17" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp17" width="15" height="11" alt="" onmouseover="this.src='img/route/p/17.gif';document.getElementById('pv17').setAttribute('class','pvH');document.getElementById('pn17').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv17').setAttribute('class','our_link_txt');document.getElementById('pn17').setAttribute('class','our_link_txt');" title="Blackfriars Bridge" border="0" /></a></div>
<div style="position:absolute;margin-top:-212px;margin-left:71px;"><a href="#18" id="pm18" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp18" width="15" height="11" alt="" onmouseover="this.src='img/route/p/18.gif';document.getElementById('pv18').setAttribute('class','pvH');document.getElementById('pn18').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv18').setAttribute('class','our_link_txt');document.getElementById('pn18').setAttribute('class','our_link_txt');" title="National Theatre" border="0" /></a></div>
<div style="position:absolute;margin-top:-194px;margin-left:63px;"><a href="#19" id="pm19" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp19" width="15" height="11" alt="" onmouseover="this.src='img/route/p/19.gif';document.getElementById('pv19').setAttribute('class','pvH');document.getElementById('pn19').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv19').setAttribute('class','our_link_txt');document.getElementById('pn19').setAttribute('class','our_link_txt');" title="The Globe" border="0" /></a></div>
<div style="position:absolute;margin-top:-216px;margin-left:123px;"><a href="#20" id="pm20" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp20" width="15" height="11" alt="" onmouseover="this.src='img/route/p/20.gif';document.getElementById('pv20').setAttribute('class','pvH');document.getElementById('pn20').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv20').setAttribute('class','our_link_txt');document.getElementById('pn20').setAttribute('class','our_link_txt');" title="Tate Modern" border="0" /></a></div>
<div style="position:absolute;margin-top:-246px;margin-left:122px;"><a href="#21" id="pm21" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp21" width="15" height="11" alt="" onmouseover="this.src='img/route/p/21.gif';document.getElementById('pv21').setAttribute('class','pvH');document.getElementById('pn21').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv21').setAttribute('class','our_link_txt');document.getElementById('pn21').setAttribute('class','our_link_txt');" title="St Paul's Cathedral" border="0" /></a></div>
<div style="position:absolute;margin-top:-228px;margin-left:131px;"><a href="#22" id="pm22" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp22" width="15" height="11" alt="" onmouseover="this.src='img/route/p/22.gif';document.getElementById('pv22').setAttribute('class','pvH');document.getElementById('pn22').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv22').setAttribute('class','our_link_txt');document.getElementById('pn22').setAttribute('class','our_link_txt');" title="Millennium Bridge" border="0" /></a></div>
<div style="position:absolute;margin-top:-224px;margin-left:159px;"><a href="#23" id="pm23" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp23" width="15" height="11" alt="" onmouseover="this.src='img/route/p/23.gif';document.getElementById('pv23').setAttribute('class','pvH');document.getElementById('pn23').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv23').setAttribute('class','our_link_txt');document.getElementById('pn23').setAttribute('class','our_link_txt');" title="Southwark Bridge" border="0" /></a></div>
<div style="position:absolute;margin-top:-207px;margin-left:166px;"><a href="#24" id="pm24" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp24" width="15" height="11" alt="" onmouseover="this.src='img/route/p/24.gif';document.getElementById('pv24').setAttribute('class','pvH');document.getElementById('pn24').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv24').setAttribute('class','our_link_txt');document.getElementById('pn24').setAttribute('class','our_link_txt');" title="Golden Hind" border="0" /></a></div>
<div style="position:absolute;margin-top:-201px;margin-left:180px;"><a href="#25" id="pm25" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp25" width="15" height="11" alt="" onmouseover="this.src='img/route/p/25.gif';document.getElementById('pv25').setAttribute('class','pvH');document.getElementById('pn25').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv25').setAttribute('class','our_link_txt');document.getElementById('pn25').setAttribute('class','our_link_txt');" title="Southwark Cathedral" border="0" /></a></div>
<div style="position:absolute;margin-top:-217px;margin-left:188px;"><a href="#26" id="pm26" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp26" width="15" height="11" alt="" onmouseover="this.src='img/route/p/26.gif';document.getElementById('pv26').setAttribute('class','pvH');document.getElementById('pn26').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv26').setAttribute('class','our_link_txt');document.getElementById('pn26').setAttribute('class','our_link_txt');" title="London Bridge" border="0" /></a></div>
<div style="position:absolute;margin-top:-236px;margin-left:185px;"><a href="#27" id="pm27" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp27" width="15" height="11" alt="" onmouseover="this.src='img/route/p/27.gif';document.getElementById('pv27').setAttribute('class','pvH');document.getElementById('pn27').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv27').setAttribute('class','our_link_txt');document.getElementById('pn27').setAttribute('class','our_link_txt');" title="Monument" border="0" /></a></div>
<div style="position:absolute;margin-top:-232px;margin-left:212px;"><a href="#28" id="pm28" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp28" width="15" height="11" alt="" onmouseover="this.src='img/route/p/28.gif';document.getElementById('pv28').setAttribute('class','pvH');document.getElementById('pn28').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv28').setAttribute('class','our_link_txt');document.getElementById('pn28').setAttribute('class','our_link_txt');" title="The Church of St. Magnus The Martyr" border="0" /></a></div>
<div style="position:absolute;margin-top:-228px;margin-left:230px;"><a href="#29" id="pm29" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp29" width="15" height="11" alt="" onmouseover="this.src='img/route/p/29.gif';document.getElementById('pv29').setAttribute('class','pvH');document.getElementById('pn29').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv29').setAttribute('class','our_link_txt');document.getElementById('pn29').setAttribute('class','our_link_txt');" title="The Custom House" border="0" /></a></div>
<div style="position:absolute;margin-top:-197px;margin-left:199px;"><a href="#30" id="pm30" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp30" width="15" height="11" alt="" onmouseover="this.src='img/route/p/30.gif';document.getElementById('pv30').setAttribute('class','pvH');document.getElementById('pn30').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv30').setAttribute('class','our_link_txt');document.getElementById('pn30').setAttribute('class','our_link_txt');" title="Hay's Wharf" border="0" /></a></div>
<div style="position:absolute;margin-top:-192px;margin-left:220px;"><a href="#31" id="pm31" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp31" width="15" height="11" alt="" onmouseover="this.src='img/route/p/31.gif';document.getElementById('pv31').setAttribute('class','pvH');document.getElementById('pn31').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv31').setAttribute('class','our_link_txt');document.getElementById('pn31').setAttribute('class','our_link_txt');" title="HMS Belfast" border="0" /></a></div>
<div style="position:absolute;margin-top:-182px;margin-left:228px;"><a href="#32" id="pm32" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp32" width="15" height="11" alt="" onmouseover="this.src='img/route/p/32.gif';document.getElementById('pv32').setAttribute('class','pvH');document.getElementById('pn32').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv32').setAttribute('class','our_link_txt');document.getElementById('pn32').setAttribute('class','our_link_txt');" title="GLA Building" border="0" /></a></div>
<div style="position:absolute;margin-top:-221px;margin-left:244px;"><a href="#33" id="pm33" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp33" width="15" height="11" alt="" onmouseover="this.src='img/route/p/33.gif';document.getElementById('pv33').setAttribute('class','pvH');document.getElementById('pn33').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv33').setAttribute('class','our_link_txt');document.getElementById('pn33').setAttribute('class','our_link_txt');" title="Tower of London" border="0" /></a></div>
<div style="position:absolute;margin-top:-199px;margin-left:243px;"><a href="#34" id="pm34" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp34" width="15" height="11" alt="" onmouseover="this.src='img/route/p/34.gif';document.getElementById('pv34').setAttribute('class','pvH');document.getElementById('pn34').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv34').setAttribute('class','our_link_txt');document.getElementById('pn34').setAttribute('class','our_link_txt');" title="Tower Bridge" border="0" /></a></div>
<div style="position:absolute;margin-top:-200px;margin-left:277px;"><a href="#35" id="pm35" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp35" width="15" height="11" alt="" onmouseover="this.src='img/route/p/35.gif';document.getElementById('pv35').setAttribute('class','pvH');document.getElementById('pn35').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv35').setAttribute('class','our_link_txt');document.getElementById('pn35').setAttribute('class','our_link_txt');" title="Wapping Police Station" border="0" /></a></div>
<div style="position:absolute;margin-top:-186px;margin-left:320px;"><a href="#36" id="pm36" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp36" width="15" height="11" alt="" onmouseover="this.src='img/route/p/36.gif';document.getElementById('pv36').setAttribute('class','pvH');document.getElementById('pn36').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv36').setAttribute('class','our_link_txt');document.getElementById('pn36').setAttribute('class','our_link_txt');" title="Town of Ramsgate Pub" border="0" /></a></div>
<div style="position:absolute;margin-top:-221px;margin-left:363px;"><a href="#37" id="pm37" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp37" width="15" height="11" alt="" onmouseover="this.src='img/route/p/37.gif';document.getElementById('pv37').setAttribute('class','pvH');document.getElementById('pn37').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv37').setAttribute('class','our_link_txt');document.getElementById('pn37').setAttribute('class','our_link_txt');" title="Prospect of Whitby" border="0" /></a></div>
<div style="position:absolute;margin-top:-18px;margin-left:582px;"><a href="#38" id="pm38" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp38" width="15" height="11" alt=""  onmouseover="this.src='img/route/p/38.gif';document.getElementById('pv38').setAttribute('class','pvH');document.getElementById('pn38').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv38').setAttribute('class','our_link_txt');document.getElementById('pn38').setAttribute('class','our_link_txt');" title="Greenwich" border="0" /></a></div>
<div style="position:absolute;margin-top:-106px;margin-left:685px;"><a href="#39" id="pm39" onclick="javascript:showdiv(this);_clearEvent(event);return false;"><img src="img/e.gif" id="pp39" width="15" height="11" alt="" onmouseover="this.src='img/route/p/39.gif';document.getElementById('pv39').setAttribute('class','pvH');document.getElementById('pn39').setAttribute('class','pnH');" onmouseout="this.src='img/e.gif';document.getElementById('pv39').setAttribute('class','our_link_txt');document.getElementById('pn39').setAttribute('class','our_link_txt');" title="Thames Barrier" border="0" /></a></div>
										 </div>
										<div class="our_boat_bottom_link">
										  <div class="our_boat_linkmain_nd1" id="anchor">
                                            <div class="our_boat_link2_nd1" id="pd01">
                                           	  <div class="our_box"><a href="javascript:void(0)" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv01" onmouseover="document.getElementById('pp01').src='img/route/p/1.gif';document.getElementById('pn01').setAttribute('class','pnH');" onmouseout="document.getElementById('pp01').src='img/e.gif';document.getElementById('pn01').setAttribute('class','our_link_txt');" class="our_link_txt_new">1</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp01').src='img/route/p/1.gif';document.getElementById('pv01').setAttribute('class','pvH');" onmouseout="document.getElementById('pp01').src='img/e.gif';document.getElementById('pv01').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn01" class="our_link_txt">Lambeth Bridge</a></div>
											  <p class="hide" id="Text01">The current structure, a five-span steel arch designed by Geoffrey Groves was opened on 12 July 1932 by King George V.<br /><br />The previous structure was a suspension bridge, 828ft long, designed by Peter W. Barlow. Sanctioned by an Act of Parliament in 1860, it opened as a toll bridge in 1862.</p>
                                            </div>
											<div class="our_boat_link2_nd1" id="pd02">
                                           	  <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv02" onmouseover="document.getElementById('pp02').src='img/route/p/2.gif';document.getElementById('pn02').setAttribute('class','pnH');" onmouseout="document.getElementById('pp02').src='img/e.gif';document.getElementById('pn02').setAttribute('class','our_link_txt');" class="our_link_txt">2</a></div>
											    <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp02').src='img/route/p/2.gif';document.getElementById('pv02').setAttribute('class','pvH');" onmouseout="document.getElementById('pp02').src='img/e.gif';document.getElementById('pv02').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn02" class="our_link_txt"> Lambeth Palace</a></div>
												<p class="hide" id="Text02">The portion of Lambeth Palace now inhabited by the Archbishop of Canterbury was built in 1834 by Edward Blore (1787-1879), who later rebuilt a large part of Buckingham Palace.<br /><br />The oldest part of the palace remaining is the Early English chapel.</p>
                                            </div>
											<div class="our_boat_link2_nd1" id="pd03">
                                           	  <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv03" onmouseover="document.getElementById('pp03').src='img/route/p/2.gif';document.getElementById('pn03').setAttribute('class','pnH');" onmouseout="document.getElementById('pp03').src='img/e.gif';document.getElementById('pn03').setAttribute('class','our_link_txt');" class="our_link_txt">3</a></div>
											    <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp03').src='img/route/p/3.gif';document.getElementById('pv03').setAttribute('class','pvH');" onmouseout="document.getElementById('pp03').src='img/e.gif';document.getElementById('pv03').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn03" class="our_link_txt">Houses of Parliament</a></div>
												<p class="hide" id="Text03">Houses up to 658 MPs. Parts of building are over 900 years old. There are 2 Chambers. Big Ben has a 13.5 ton bell within.</p>
                                            </div>
											<div class="our_boat_link2_nd1" id="pd04">
                                           	  <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv04" onmouseover="document.getElementById('pp04').src='img/route/p/4.gif';document.getElementById('pn04').setAttribute('class','pnH');" onmouseout="document.getElementById('pp04').src='img/e.gif';document.getElementById('pn04').setAttribute('class','our_link_txt');" class="our_link_txt">4</a></div>
											    <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp04').src='img/route/p/4.gif';document.getElementById('pv04').setAttribute('class','pvH');" onmouseout="document.getElementById('pp04').src='img/e.gif';document.getElementById('pv04').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn04" class="our_link_txt">Westminster Bridge</a></div>
												<p class="hide" id="Text04">The building of Westminster Bridge begun in 1739, and was finished in 1750.<br /><br />The original Bridge was built entirely of stone, and extends over the river at a place where it is 1,223 feet broad, which is over 300 feet broader than at London Bridge.</p>
                                            </div>
											<div class="our_boat_link2_nd1" id="pd05">
                                           	  <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv05" onmouseover="document.getElementById('pp05').src='img/route/p/5.gif';document.getElementById('pn05').setAttribute('class','pnH');" onmouseout="document.getElementById('pp05').src='img/e.gif';document.getElementById('pn05').setAttribute('class','our_link_txt');" class="our_link_txt">5</a></div>
											    <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp05').src='img/route/p/5.gif';document.getElementById('pv05').setAttribute('class','pvH');" onmouseout="document.getElementById('pp05').src='img/e.gif';document.getElementById('pv05').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn05" class="our_link_txt"> Portcullis House</a></div>
												<p class="hide"  id="Text05">Portcullis House opened in 2001 and today houses offices for 450 MPs.<br /><br />Office space has traditionally been very hard to find in the Palace of Westminster and nearby buildings, so in 1998 the House authorised the construction of this new building.</p>
                                            </div>
											<div class="our_boat_link2_nd1" id="pd06">
                                           	  <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv06" onmouseover="document.getElementById('pp06').src='img/route/p/6.gif';document.getElementById('pn06').setAttribute('class','pnH');" onmouseout="document.getElementById('pp06').src='img/e.gif';document.getElementById('pn06').setAttribute('class','our_link_txt');" class="our_link_txt">6</a></div>
											    <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp06').src='img/route/p/6.gif';document.getElementById('pv06').setAttribute('class','pvH');" onmouseout="document.getElementById('pp06').src='img/e.gif';document.getElementById('pv06').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn06" class="our_link_txt">County Hall</a></div>
												<p class="hide"  id="Text06">Construction of County Hall started in 1911 and it was opened in 1933 by King George V.<br /><br />The main building was designed by Ralph Knott and is six storeys, faced in Portland Stone and is in an 'Edwardian Baroque' style.<br /><br />It is at the corner of Bridge Street and Victoria Embankment, overlooks the River Thames, and sits above Westminster tube station. It was designed at the same time as the station by the same designers, Michael Hopkins &amp; Partners.</p>
                                            </div>
											<div class="our_boat_link2_nd1"  id="pd07">
                                           	  <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv07" onmouseover="document.getElementById('pp07').src='img/route/p/7.gif';document.getElementById('pn07').setAttribute('class','pnH');" onmouseout="document.getElementById('pp07').src='img/e.gif';document.getElementById('pn07').setAttribute('class','our_link_txt');" class="our_link_txt">7</a></div>
											    <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp07').src='img/route/p/7.gif';document.getElementById('pv07').setAttribute('class','pvH');" onmouseout="document.getElementById('pp07').src='img/e.gif';document.getElementById('pv07').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn07" class="our_link_txt">MOD</a></div>
												<p class="hide"  id="Text07">Originally providing accommodation for the Board of Trade and the Air Ministry, the MOD 'Main Building' was built between 1938 and 1959 to designs by the architect E. Vincent Harris.<br /><br />The Main Building was to be Harris' last major work, and was one of the last major public buildings in the Neoclassical style to built. As such it is a fitting memorial to Harris, described by one of his assistants as 'a man completely dedicated to classic...</p>
                                            </div>
											<div class="our_boat_link2_nd1" id="pd08">
                                           	  <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv08" onmouseover="document.getElementById('pp08').src='img/route/p/8.gif';document.getElementById('pn08').setAttribute('class','pnH');" onmouseout="document.getElementById('pp08').src='img/e.gif';document.getElementById('pn08').setAttribute('class','our_link_txt');" class="our_link_txt">8</a></div>
											    <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp08').src='img/route/p/8.gif';document.getElementById('pv08').setAttribute('class','pvH');" onmouseout="document.getElementById('pp08').src='img/e.gif';document.getElementById('pv08').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn08" class="our_link_txt">London Eye</a></div>
												<p class="hide" id="Text08">440 foot to top, with 32 capsules travelling at 2.5 miles per hour. This is an Anglo German Dutch, Czeck Italian engineering triumph!</p>
                                            </div>
											<div class="our_boat_link2_nd1" id="pd09">
                                           	  <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv09" onmouseover="document.getElementById('pp09').src='img/route/p/9.gif';document.getElementById('pn09').setAttribute('class','pnH');" onmouseout="document.getElementById('pp09').src='img/e.gif';document.getElementById('pn09').setAttribute('class','our_link_txt');" class="our_link_txt">9</a></div>
											    <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp09').src='img/route/p/9.gif';document.getElementById('pv09').setAttribute('class','pvH');" onmouseout="document.getElementById('pp09').src='img/e.gif';document.getElementById('pv09').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn09" class="our_link_txt">Golden Jubilee Bridges</a></div>
												<p class="hide" id="Text09">The Golden Jubilee Bridges were opened on 2 July 2003.<br /><br />Over forty groups submitted designs for the new Bridges with the London-based winning team comprising architects Lifschutz Davidson, engineers WSP Group and quantity surveyors Davis Langdon &amp; Everest.</p>
                                            </div>
											<div class="our_boat_link2_nd1" id="pd10">
                                           	  <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv10" onmouseover="document.getElementById('pp10').src='img/route/p/10.gif';document.getElementById('pn10').setAttribute('class','pnH');" onmouseout="document.getElementById('pp10').src='img/e.gif';document.getElementById('pn10').setAttribute('class','our_link_txt');" class="our_link_txt">10</a></div>
											    <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp10').src='img/route/p/10.gif';document.getElementById('pv10').setAttribute('class','pvH');" onmouseout="document.getElementById('pp10').src='img/e.gif';document.getElementById('pv10').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn10" class="our_link_txt">Charing Cross Station</a></div>
												<p class="hide" id="Text10">Charing Cross was opened in 1864 and was the product of the Southern Eastern Railway's need to extend westward from London Bridge to get its passengers from Kent right into the heart of London.<br /><br />Situated on the forecourt of the stations is the Eleanor Cross, from which point road distances from London are measured.</p>
                                            </div>
									      </div>
										  <div class="our_boat_linkmain2_nd1">
                                            <div class="our_boat_link2_nd1" id="pd11">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv11" onmouseover="document.getElementById('pp11').src='img/route/p/11.gif';document.getElementById('pn11').setAttribute('class','pnH');" onmouseout="document.getElementById('pp11').src='img/e.gif';document.getElementById('pn11').setAttribute('class','our_link_txt');" class="our_link_txt">11</a></div>
                                              <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp11').src='img/route/p/11.gif';document.getElementById('pv11').setAttribute('class','pvH');" onmouseout="document.getElementById('pp11').src='img/e.gif';document.getElementById('pv11').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn11" class="our_link_txt">South Bank Centre</a></div>
											  <p class="hide" id="Text11">The South Bank Centre was built in 1951 as part of the Festival of Britain.<br /><br />The South Bank Centre comprises The Royal Festival Hall, Queen Elizabeth Hall, the Purcell Room and the Hayward Gallery. It shares the site with the independently managed National Theatre, the National Film Theatre and the new Museum of the Moving Image.</p>
                                            </div>
										    <div class="our_boat_link2_nd1" id="pd12">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv12" onmouseover="document.getElementById('pp12').src='img/route/p/12.gif';document.getElementById('pn12').setAttribute('class','pnH');" onmouseout="document.getElementById('pp12').src='img/e.gif';document.getElementById('pn12').setAttribute('class','our_link_txt');" class="our_link_txt">12</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp12').src='img/route/p/12.gif';document.getElementById('pv12').setAttribute('class','pvH');" onmouseout="document.getElementById('pp12').src='img/e.gif';document.getElementById('pv12').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn12" class="our_link_txt">Shell Mex House</a></div>
											  <p class="hide" id="Text12">The Shell Mex House building started life as the Cecil Hotel in 1886 and was the largest hotel in Europe at the time with 800 rooms.<br /><br />After it was purchased by Shell Mex in 1930, the river fac,ade was remodelled to create a 13 storey building with a central clock tower.</p>
									        </div>
										    <div class="our_boat_link2_nd1"  id="pd13">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv13" onmouseover="document.getElementById('pp13').src='img/route/p/13.gif';document.getElementById('pn13').setAttribute('class','pnH');" onmouseout="document.getElementById('pp13').src='img/e.gif';document.getElementById('pn13').setAttribute('class','our_link_txt');" class="our_link_txt">13</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp13').src='img/route/p/13.gif';document.getElementById('pv13').setAttribute('class','pvH');" onmouseout="document.getElementById('pp13').src='img/e.gif';document.getElementById('pv13').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn13" class="our_link_txt">Waterloo Bridge</a></div>
											  <p class="hide" id="Text13">The new Waterloo Bridge was partially opened in 1942 and completed in 1945. It was the only Thames bridge to have been damaged by German bombers during World War II.<br /><br />The first bridge on the site was designed by John Rennie and opened in 1817 as a toll bridge. Before its opening it was known as 'Strand Bridge'. It was nationalised in 1878 and given to the Metropolitan Board of Works.</p>
									        </div>
										    <div class="our_boat_link2_nd1" id="pd14">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv14" onmouseover="document.getElementById('pp14').src='img/route/p/14.gif';document.getElementById('pn14').setAttribute('class','pnH');" onmouseout="document.getElementById('pp14').src='img/e.gif';document.getElementById('pn14').setAttribute('class','our_link_txt');" class="our_link_txt">14</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp14').src='img/route/p/14.gif';document.getElementById('pv14').setAttribute('class','pvH');" onmouseout="document.getElementById('pp14').src='img/e.gif';document.getElementById('pv14').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn14" class="our_link_txt">Somerset House</a></div>
											  <p class="hide" id="Text14">Somerset House takes its name from the London home of Edward Seymour, Duke of Somerset, who commissioned a riverside mansion on the site in 1547.<br /><br />When he fell from grace in 1551 (being executed for treason the following year), the building passed to the Crown and was used by Princess Elizabeth for some years before she was crowned Queen Elizabeth I in 1558.</p>
									        </div>
										    <div class="our_boat_link2_nd1" id="pd15">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv15" onmouseover="document.getElementById('pp15').src='img/route/p/15.gif';document.getElementById('pn15').setAttribute('class','pnH');" onmouseout="document.getElementById('pp15').src='img/e.gif';document.getElementById('pn15').setAttribute('class','our_link_txt');" class="our_link_txt">15</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp15').src='img/route/p/15.gif';document.getElementById('pv15').setAttribute('class','pvH');" onmouseout="document.getElementById('pp15').src='img/e.gif';document.getElementById('pv15').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn15" class="our_link_txt">Temple Arch</a></div>
											  <p class="hide" id="Text15">This embraces two of the four Inns of Court, the Middle Temple and the Inner Temple. (The remaining two are Lincoln's and Gray's Inn).<br /><br />The name comes from the Knights Templar, an order which used to protect pilgrims to the Holy Land. The order was based here until it was suppressed by the Crown because its power was viewed as a threat.<br /><br />In Middle Temple Hall, the play, Twelth Night was performed in front of King James 1st. William Shakespeare performed one of the roles!<br /><br />The Temple Church is one of only 5 Churches with a round nave. The interior will appear soon in what will no doubt be a very successful film: The Da Vinci Code starring Tom Hanks.</p>
									        </div>
										    <div class="our_boat_link2_nd1" id="pd16">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv16" onmouseover="document.getElementById('pp16').src='img/route/p/16.gif';document.getElementById('pn16').setAttribute('class','pnH');" onmouseout="document.getElementById('pp16').src='img/e.gif';document.getElementById('pn16').setAttribute('class','our_link_txt');" class="our_link_txt">16</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp16').src='img/route/p/16.gif';document.getElementById('pv16').setAttribute('class','pvH');" onmouseout="document.getElementById('pp16').src='img/e.gif';document.getElementById('pv16').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn16" class="our_link_txt">Oxo Tower</a></div>
											  <p class="hide" id="Text16">At the turn of the century a power station was built on this site to supply electricity to the Post Office. In the late 1920s the site was purchased by the Liebig Extract of Meat Company.<br /><br />Its architect, Albert W Moore, proposed to spell out the name in electric lights on a tower but was refused permission. He came back with OXO incorporated as windows in 'an elemental geometric form' on all four sides of the tower.</p>
									        </div>
										    <div class="our_boat_link2_nd1" id="pd17">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv17" onmouseover="document.getElementById('pp17').src='img/route/p/17.gif';document.getElementById('pn17').setAttribute('class','pnH');" onmouseout="document.getElementById('pp17').src='img/e.gif';document.getElementById('pn17').setAttribute('class','our_link_txt');" class="our_link_txt">17</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp17').src='img/route/p/17.gif';document.getElementById('pv17').setAttribute('class','pvH');" onmouseout="document.getElementById('pp17').src='img/e.gif';document.getElementById('pv17').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn17" class="our_link_txt">Blackfriars Bridge</a></div>
											  <p class="hide" id="Text17">The current Blackfriars Bridge was completed in 1869 and consists of five wrought iron arches built to a design by Joseph Cubitt.<br /><br />The bridge became internationally notorious in 1982, when the Italian banker Roberto Calvi was found hanged below one of its arches in what was originally believed to be a suicide, but is now officially regarded as a murder.</p>
									        </div>
										    <div class="our_boat_link2_nd1" id="pd18">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv18" onmouseover="document.getElementById('pp18').src='img/route/p/18.gif';document.getElementById('pn18').setAttribute('class','pnH');" onmouseout="document.getElementById('pp18').src='img/e.gif';document.getElementById('pn18').setAttribute('class','our_link_txt');" class="our_link_txt">18</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp18').src='img/route/p/18.gif';document.getElementById('pv18').setAttribute('class','pvH');" onmouseout="document.getElementById('pp18').src='img/e.gif';document.getElementById('pv18').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn18" class="our_link_txt">National Theatre</a></div>
											  <p class="hide" id="Text18">Brutalist, concrete building, loved by many but disliked by countless others.<br /><br />It has 3 Theatres, with the largest called the Olivier. The seats are purple which is said to be Olivier's favourite colour.</p>
									        </div>
										    <div class="our_boat_link2_nd1" id="pd19">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv19" onmouseover="document.getElementById('pp19').src='img/route/p/19.gif';document.getElementById('pn19').setAttribute('class','pnH');" onmouseout="document.getElementById('pp19').src='img/e.gif';document.getElementById('pn19').setAttribute('class','our_link_txt');" class="our_link_txt">19</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp19').src='img/route/p/19.gif';document.getElementById('pv19').setAttribute('class','pvH');" onmouseout="document.getElementById('pp19').src='img/e.gif';document.getElementById('pv19').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn19" class="our_link_txt">The Globe</a></div>
											  <p class="hide" id="Text19">Brainchild of Sam Wanamaker, American actor/director - now in its 10th year.<br /><br />500 standing only seats available for most performances on the day of production. This is the only building in London with a thatched roof.</p>
									        </div>
										    <div class="our_boat_link2_nd1" id="pd20">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv20" onmouseover="document.getElementById('pp20').src='img/route/p/20.gif';document.getElementById('pn20').setAttribute('class','pnH');" onmouseout="document.getElementById('pp20').src='img/e.gif';document.getElementById('pn20').setAttribute('class','our_link_txt');" class="our_link_txt">20</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp20').src='img/route/p/20.gif';document.getElementById('pv20').setAttribute('class','pvH');" onmouseout="document.getElementById('pp20').src='img/e.gif';document.getElementById('pv20').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn20" class="our_link_txt">Tate Modern</a></div>
											  <p class="hide" id="Text20">The Tate Modern is housed in the former Bankside Power Station, which was built in two stages between 1947 and 1963. The building was converted by architects Herzog &amp; de Meuron and opened as the Tate Modern on 12 May 2000.<br /><br />The collection includes major works by Matisse, Picasso and Rothko as well as contemporary work by artists such as Richard Deacon, Emma Kay, Mariko Mori and Gerhard Richter.</p>
									        </div>
									      </div>
										  <div class="our_boat_linkmain2_nd1">
                                            <div class="our_boat_link2_nd1" id="pd21">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv21" onmouseover="document.getElementById('pp21').src='img/route/p/21.gif';document.getElementById('pn21').setAttribute('class','pnH');" onmouseout="document.getElementById('pp21').src='img/e.gif';document.getElementById('pn21').setAttribute('class','our_link_txt');" class="our_link_txt">21</a></div>
                                              <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp21').src='img/route/p/21.gif';document.getElementById('pv21').setAttribute('class','pvH');" onmouseout="document.getElementById('pp21').src='img/e.gif';document.getElementById('pv21').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn21" class="our_link_txt">St Paul's Cathedral</a></div>
											  <p class="hide" id="Text21">365 feet to top, and completed in 35 years, the masterpiece of Sir Christopher Wren who along with Wellington and Nelson are buried in the Crypt.</p>
                                            </div>
										    <div class="our_boat_link2_nd1" id="pd22">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv22" onmouseover="document.getElementById('pp22').src='img/route/p/22.gif';document.getElementById('pn22').setAttribute('class','pnH');" onmouseout="document.getElementById('pp22').src='img/e.gif';document.getElementById('pn22').setAttribute('class','our_link_txt');" class="our_link_txt">22</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp22').src='img/route/p/22.gif';document.getElementById('pv22').setAttribute('class','pvH');" onmouseout="document.getElementById('pp22').src='img/e.gif';document.getElementById('pv22').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn22" class="our_link_txt">Millennium Bridge</a></div>
											  <p class="hide" id="Text22">On Tuesday 9 May, the Millennium Bridge, was inaugurated with a special ceremony of dedication by HM The Queen. The Bridge was designed jointly by Arup, Foster and Partners and leading British sculptor Sir Anthony Caro.<br /><br />It was the first pedestrian river crossing over the Thames in central London for more than a century. It links the City of London at St. Paul's Cathedral with the Tate Modern Gallery at Bankside.</p>
									        </div>
										    <div class="our_boat_link2_nd1"  id="pd23">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv23" onmouseover="document.getElementById('pp23').src='img/route/p/23.gif';document.getElementById('pn23').setAttribute('class','pnH');" onmouseout="document.getElementById('pp23').src='img/e.gif';document.getElementById('pn23').setAttribute('class','our_link_txt');" class="our_link_txt">23</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp23').src='img/route/p/23.gif';document.getElementById('pv23').setAttribute('class','pvH');" onmouseout="document.getElementById('pp23').src='img/e.gif';document.getElementById('pv23').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn23" class="our_link_txt">Southwark Bridge</a></div>
											  <p class="hide" id="Text23">Southwark Bridge was designed by Ernest George and Basil Mott and opened in 1921. A previous bridge on the site was designed by John Rennie and opened in 1819.</p>
									        </div>
										    <div class="our_boat_link2_nd1" id="pd24">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv24" onmouseover="document.getElementById('pp24').src='img/route/p/24.gif';document.getElementById('pn24').setAttribute('class','pnH');" onmouseout="document.getElementById('pp24').src='img/e.gif';document.getElementById('pn24').setAttribute('class','our_link_txt');" class="our_link_txt">24</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp24').src='img/route/p/24.gif';document.getElementById('pv24').setAttribute('class','pvH');" onmouseout="document.getElementById('pp24').src='img/e.gif';document.getElementById('pv24').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn24" class="our_link_txt">Golden Hind</a></div>
											  <p class="hide" id="Text24">The Golden Hind is best known for its global circumnavigation between 1577 and 1580, under Captain Francis Drake.<br /><br />The Golden Hind was originally known as the Pelican and was renamed in mid-voyage (1577) by Drake as he prepared to enter the Straits of Magellan.</p>
									        </div>
										    <div class="our_boat_link2_nd1" id="pd25">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv25" onmouseover="document.getElementById('pp25').src='img/route/p/25.gif';document.getElementById('pn25').setAttribute('class','pnH');" onmouseout="document.getElementById('pp25').src='img/e.gif';document.getElementById('pn25').setAttribute('class','our_link_txt');" class="our_link_txt">25</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp25').src='img/route/p/25.gif';document.getElementById('pv25').setAttribute('class','pvH');" onmouseout="document.getElementById('pp25').src='img/e.gif';document.getElementById('pv25').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn25" class="our_link_txt">Southwark Cathedral</a></div>
											  <p class="hide" id="Text25">The main structure was built between 1220 and 1420. It was a parish church which only became a cathedral early in the 20th century.<br /><br />In 2002, Southwark Cathedral's Millennium buildings received an award for being one of the best new buildings of the year. John Harvard, one of the founders of the Harvard Line, and a pilgrim father who went to America on the Mayflower, is buried in the graveyard.</p>
									        </div>
										    <div class="our_boat_link2_nd1"  id="pd26">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv26" onmouseover="document.getElementById('pp26').src='img/route/p/26.gif';document.getElementById('pn26').setAttribute('class','pnH');" onmouseout="document.getElementById('pp26').src='img/e.gif';document.getElementById('pn26').setAttribute('class','our_link_txt');" class="our_link_txt">26</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp26').src='img/route/p/26.gif';document.getElementById('pv26').setAttribute('class','pvH');" onmouseout="document.getElementById('pp26').src='img/e.gif';document.getElementById('pv26').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn26" class="our_link_txt">London Bridge</a></div>
											  <p class="hide" id="Text26">The current version of London Bridge was designed by engineer John Rennie and completed by his son (of the same name) over a seven-year period from 1824 to 1831.<br /><br />The Bridge was constructed from Dartmoor granite, with a length of 928 feet and a width of 49 feet. It was widened in 1902-1904 in an attempt to combat London's chronic traffic congestion.</p>
									        </div>
										    <div class="our_boat_link2_nd1" id="pd27">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv27" onmouseover="document.getElementById('pp27').src='img/route/p/27.gif';document.getElementById('pn27').setAttribute('class','pnH');" onmouseout="document.getElementById('pp27').src='img/e.gif';document.getElementById('pn27').setAttribute('class','our_link_txt');" class="our_link_txt">27</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp27').src='img/route/p/27.gif';document.getElementById('pv27').setAttribute('class','pvH');" onmouseout="document.getElementById('pp27').src='img/e.gif';document.getElementById('pv27').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn27" class="our_link_txt">Monument</a></div>
											  <p class="hide" id="Text27">The Monument was constructed between 1671 and 1677 to commemorate the Great Fire of London.<br /><br />At the time it was the tallest freestanding stone column in the world. If it is laid out lengthways then the flame would reach Pudding Lane where the great fire started.</p>
									        </div>
										    <div class="our_boat_link2_nd1" id="pd28">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv28" onmouseover="document.getElementById('pp28').src='img/route/p/28.gif';document.getElementById('pn28').setAttribute('class','pnH');" onmouseout="document.getElementById('pp28').src='img/e.gif';document.getElementById('pn28').setAttribute('class','our_link_txt');" class="our_link_txt">28</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp28').src='img/route/p/28.gif';document.getElementById('pv28').setAttribute('class','pvH');" onmouseout="document.getElementById('pp28').src='img/e.gif';document.getElementById('pv28').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn28" class="our_link_txt">Magnus The Martyr</a></div>
											  <p class="hide" id="Text28">The original Church of St Magnus the Martyr was built in 1176; after the Great Fire of London in 1666, Sir Christopher Wren rebuilt the church on the same site.<br /><br />Projecting from the west side is a large clock given by Sir Charles Duncombe in 1700, this was once one of the most familiar clocks in London but since the 1920s it has been hidden by Adelaide House.</p>
									        </div>
										    <div class="our_boat_link2_nd1"  id="pd29">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv29" onmouseover="document.getElementById('pp29').src='img/route/p/29.gif';document.getElementById('pn29').setAttribute('class','pnH');" onmouseout="document.getElementById('pp29').src='img/e.gif';document.getElementById('pn29').setAttribute('class','our_link_txt');" class="our_link_txt">29</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp29').src='img/route/p/29.gif';document.getElementById('pv29').setAttribute('class','pvH');" onmouseout="document.getElementById('pp29').src='img/e.gif';document.getElementById('pv29').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn29" class="our_link_txt">The Custom House</a></div>
											  <p class="hide" id="Text29">The first stone of the new Customs House was laid on the 25th of Oct 18l3, however the building was not opened for public business until the 12th of May, 1817.<br /><br />The south face of the building (towards the Thames), together with those towards the east and west, are faced with Portland stone; while the north face of the building built chiefly of brick.</p>
									        </div>
										    <div class="our_boat_link2_nd1" id="pd30">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv30" onmouseover="document.getElementById('pp30').src='img/route/p/30.gif';document.getElementById('pn30').setAttribute('class','pnH');" onmouseout="document.getElementById('pp30').src='img/e.gif';document.getElementById('pn30').setAttribute('class','our_link_txt');" class="our_link_txt">30</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp30').src='img/route/p/30.gif';document.getElementById('pv30').setAttribute('class','pvH');" onmouseout="document.getElementById('pp30').src='img/e.gif';document.getElementById('pv30').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn30" class="our_link_txt">Hay’s Wharf</a></div>
											  <p class="hide" id="Text30">The current Hays Wharf was designed by Architects Harry Stuart Goodhart-Rendel, construction began in 1931.<br /><br />From the 18th century onwards the Pool of London became known as London's Larder as all the food imported to London came through the docks at Hays Wharf.</p>
									        </div>
									      </div>
										  <div class="our_boat_linkmain3_nd1">
                                            <div class="our_boat_link2_nd1" id="pd31">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv31" onmouseover="document.getElementById('pp31').src='img/route/p/31.gif';document.getElementById('pn31').setAttribute('class','pnH');" onmouseout="document.getElementById('pp31').src='img/e.gif';document.getElementById('pn31').setAttribute('class','our_link_txt');" class="our_link_txt">31</a></div>
                                              <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp31').src='img/route/p/31.gif';document.getElementById('pv31').setAttribute('class','pvH');" onmouseout="document.getElementById('pp31').src='img/e.gif';document.getElementById('pv31').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn31" class="our_link_txt">HMS Belfast</a></div>
											  <p class="hide" id="Text31">Floating Museum since 1971. Guns can fire up to 14 miles. Saw action in North Atlantic Campaign in 1942. 11,500 tons in weight.<br /><br />Top speed of about 33 knots; compare this to the speed of the RIB.</p>
                                            </div>
										    <div class="our_boat_link2_nd1" id="pd32">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv32" onmouseover="document.getElementById('pp32').src='img/route/p/32.gif';document.getElementById('pn32').setAttribute('class','pnH');" onmouseout="document.getElementById('pp32').src='img/e.gif';document.getElementById('pn32').setAttribute('class','our_link_txt');" class="our_link_txt">32</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp32').src='img/route/p/32.gif';document.getElementById('pv32').setAttribute('class','pvH');" onmouseout="document.getElementById('pp32').src='img/e.gif';document.getElementById('pv32').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn32" class="our_link_txt">GLA Building</a></div>
											  <p class="hide" id="Text32">Where our Mayor, Ken Livingston conducts business with 26 elected members of the Greater London Assembly.</p>
									        </div>
										    <div class="our_boat_link2_nd1" id="pd33">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv33" onmouseover="document.getElementById('pp33').src='img/route/p/33.gif';document.getElementById('pn33').setAttribute('class','pnH');" onmouseout="document.getElementById('pp33').src='img/e.gif';document.getElementById('pn33').setAttribute('class','our_link_txt');" class="our_link_txt">33</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp33').src='img/route/p/33.gif';document.getElementById('pv33').setAttribute('class','pvH');" onmouseout="document.getElementById('pp33').src='img/e.gif';document.getElementById('pv33').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn33" class="our_link_txt">Tower of London</a></div>
											  <p class="hide" id="Text33">1000 years of history, with the Crown Jewels kept there. There are 8 Ravens named after mythological Welsh and Norwegian Gods.<br /><br />Yeoman Warders date back to the time when they were the personal bodyguard to King Henry 8th.</p>
									        </div>
										    <div class="our_boat_link2_nd1" id="pd34">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv34" onmouseover="document.getElementById('pp34').src='img/route/p/34.gif';document.getElementById('pn34').setAttribute('class','pnH');" onmouseout="document.getElementById('pp34').src='img/e.gif';document.getElementById('pn34').setAttribute('class','our_link_txt');" class="our_link_txt">34</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp34').src='img/route/p/34.gif';document.getElementById('pv34').setAttribute('class','pvH');" onmouseout="document.getElementById('pp34').src='img/e.gif';document.getElementById('pv34').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn34" class="our_link_txt">Tower Bridge</a></div>
											  <p class="hide" id="Text34">Opened 1894 by Prince of Wales, the future Edward 7th. Opens on average 4 times week.</p>
									        </div>
										    <div class="our_boat_link2_nd1" id="pd35">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv35" onmouseover="document.getElementById('pp35').src='img/route/p/35.gif';document.getElementById('pn35').setAttribute('class','pnH');" onmouseout="document.getElementById('pp35').src='img/e.gif';document.getElementById('pn35').setAttribute('class','our_link_txt');" class="our_link_txt">35</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp35').src='img/route/p/35.gif';document.getElementById('pv35').setAttribute('class','pvH');" onmouseout="document.getElementById('pp35').src='img/e.gif';document.getElementById('pv35').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn35" class="our_link_txt">Wapping Police Station</a></div>
											  <p class="hide" id="Text35">Oldest part of the Metropolitan Police dating from 1797.</p>
									        </div>
										    <div class="our_boat_link2_nd1" id="pd36">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv36" onmouseover="document.getElementById('pp36').src='img/route/p/36.gif';document.getElementById('pn36').setAttribute('class','pnH');" onmouseout="document.getElementById('pp36').src='img/e.gif';document.getElementById('pn36').setAttribute('class','our_link_txt');" class="our_link_txt">36</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp36').src='img/route/p/36.gif';document.getElementById('pv36').setAttribute('class','pvH');" onmouseout="document.getElementById('pp36').src='img/e.gif';document.getElementById('pv36').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn36" class="our_link_txt">Town of Ramsgate Pub</a></div>
											  <p class="hide" id="Text36">Where the Hanging Judge Jefferies was cornered by a mob and eventually hanged himself.</p>
									        </div>
										    <div class="our_boat_link2_nd1" id="pd37">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv37" onmouseover="document.getElementById('pp37').src='img/route/p/37.gif';document.getElementById('pn37').setAttribute('class','pnH');" onmouseout="document.getElementById('pp37').src='img/e.gif';document.getElementById('pn37').setAttribute('class','our_link_txt');" class="our_link_txt">37</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp37').src='img/route/p/37.gif';document.getElementById('pv37').setAttribute('class','pvH');" onmouseout="document.getElementById('pp37').src='img/e.gif';document.getElementById('pv37').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn37" class="our_link_txt">Prospect of Whitby</a></div>
											  <p class="hide" id="Text37">This has been an ale house during the reign of 22 Kings and Queens.</p>
									        </div>
										    <div class="our_boat_link2_nd1" id="pd38">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv38" onmouseover="document.getElementById('pp38').src='img/route/p/38.gif';document.getElementById('pn38').setAttribute('class','pnH');" onmouseout="document.getElementById('pp38').src='img/e.gif';document.getElementById('pn38').setAttribute('class','our_link_txt');" class="our_link_txt">38</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp38').src='img/route/p/38.gif';document.getElementById('pv38').setAttribute('class','pvH');" onmouseout="document.getElementById('pp38').src='img/e.gif';document.getElementById('pv38').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn38" class="our_link_txt">Greenwich</a></div>
											  <p class="hide" id="Text38">Site of an ancient palace in which Henry 8th was born and also his son Edward 6th. The Observatory was built for King Charles 2nd by Sir Christopher Wren.<br /><br />The National Maritime Museum is one of the finest in the world. This has an interesting Exhibition about Nelson and Napoleon.</p>
									        </div>
										    <div class="our_boat_link2_nd1" id="pd39">
                                              <div class="our_box"><a href="#" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pv39" onmouseover="document.getElementById('pp39').src='img/route/p/39.gif';document.getElementById('pn39').setAttribute('class','pnH');" onmouseout="document.getElementById('pp39').src='img/e.gif';document.getElementById('pn39').setAttribute('class','our_link_txt');" class="our_link_txt">39</a></div>
										      <div class="our_boat_link_nd1"><a href="#" onmouseover="document.getElementById('pp39').src='img/route/p/39.gif';document.getElementById('pv39').setAttribute('class','pvH');" onmouseout="document.getElementById('pp39').src='img/e.gif';document.getElementById('pv39').setAttribute('class','our_link_txt');" onclick="javascript:showdiv(this);_clearEvent(event);return false;" id="pn39" class="our_link_txt">Thames Barrier</a></div>
											  <p class="hide" id="Text39">The Thames Barrier has been described as the eighth wonder of the world. It is certainly a very impressive work of engineering.<br /><br />High water level at London Bridge has risen about two and a half feet per century, due to the melting of the polar ice caps and the activities of Man.</p>
									        </div>
										    
									      </div>
										</div>
										<div class="view_interactive_btn"><a href="javascript: openwind('flash-tour.htm', 780, 500, 'no');"><img src="img/viewintflt.gif" width="145" height="32" alt="" onmouseover="this.src='img/viewintflt_.gif'" onmouseout="this.src='img/viewintflt.gif'" border="0" /></a></div>
										  </div>
										  
										  </div>
								        <div class="or_bt_bottom"><img src="images/our_boat_rute_bottom.png" alt="" /></div>
										  </div>